import SwiftUI

struct DisclaimerView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("Disclaimer")
                    .font(.title2)
                    .fontWeight(.bold)

                Text("This app provides sports betting insights for informational purposes only. It does not place wagers, process payments, or guarantee outcomes. Please wager responsibly and comply with local laws and regulations.")

                Text("All projections are generated by models and may be inaccurate. Use at your own risk.")
            }
            .padding()
        }
        .navigationTitle("Disclaimer")
    }
}

#Preview {
    NavigationStack {
        DisclaimerView()
    }
}
